from utils.drawing import draw_graph_to_file
from utils.general import ExchangeNotInCollectionsError, get_exchanges_for_market
from utils.multi_exchange import create_multi_exchange_graph, create_weighted_multi_exchange_digraph, \
    multi_graph_to_log_graph